const test = require('node:test');
const assert = require('node:assert/strict');
const { deriveAuthorizedMutationTools } = require('../aiAgentRuntime');

const sameTools = (actual, expected, prompt) => assert.deepEqual([...actual].sort(), [...expected].sort(), prompt);

const executableCases = [
  ['새 폴더 만들어줘', ['create_folder']],
  ['/사진/2026 폴더를 생성해주세요', ['create_folder']],
  ['백업 디렉터리 생성해 주세요', ['create_folder']],
  ['보고서.txt 파일을 만들어줘', ['write_text_file']],
  ['/메모.txt 파일에 내용을 저장해줘', ['write_text_file']],
  ['todo.md 파일을 작성해주세요', ['write_text_file']],
  ['기존 메모 끝에 한 줄 추가해줘', ['append_text_file']],
  ['일지 파일에 오늘 기록을 덧붙여줘', ['append_text_file']],
  ['README 내용 끝에 문장을 추가해주세요', ['append_text_file']],
  ['사진 폴더를 백업 폴더로 복사해줘', ['copy_item']],
  ['이 문서를 복제해주세요', ['copy_item']],
  ['report.pdf 사본을 복사해줘', ['copy_item']],
  ['a.txt를 archive로 옮겨줘', ['move_item']],
  ['사진을 보관함으로 이동해주세요', ['move_item']],
  ['old.txt 이름을 new.txt로 바꿔줘', ['move_item']],
  ['old.txt를 삭제해줘', ['trash_item']],
  ['tmp 폴더를 지워줘', ['trash_item']],
  ['report.pdf를 휴지통으로 보내줘', ['trash_item']],
  ['다운로드 폴더를 날짜별로 정리해주세요', ['organize_files_by_modified_date']],
  ['사진 파일을 월별로 분류해줘', ['organize_files_by_modified_date']],
  ['어제 작업 파일을 정리해줘', ['organize_files_by_modified_date']],
  ['민수에게 친구 요청 보내줘', ['send_friend_request']],
  ['영희를 친구로 추가해주세요', ['send_friend_request']],
  ['사용자 kim에게 친구 요청을 전송해줘', ['send_friend_request']],
  ['민수를 차단해줘', ['set_user_blocked']],
  ['영희 차단을 해제해주세요', ['set_user_blocked']],
  ['kim 사용자를 차단해 주세요', ['set_user_blocked']],
  ['민수에게 늦는다고 메시지 보내줘', ['send_chat_message']],
  ['영희에게 안녕이라고 채팅 전송해줘', ['send_chat_message']],
  ['kim에게 회의가 취소됐다고 알려줘', ['send_chat_message']],
  ['민수에게 보고서 파일을 보내줘', ['send_file_to_user']],
  ['영희에게 사진 폴더를 공유해주세요', ['send_file_to_user']],
  ['kim에게 문서를 전송해줘', ['send_file_to_user']],
  ['회의 노트를 만들어줘', ['create_note']],
  ['새 Markdown 페이지를 생성해주세요', ['create_note']],
  ['Python 코드 노트를 작성해줘', ['create_note']],
  ['회의 노트 내용을 수정해줘', ['update_note']],
  ['이 페이지 제목을 바꿔줘', ['update_note']],
  ['선택한 노트를 편집해주세요', ['update_note']],
  ['회의 노트를 휴지통으로 보내줘', ['trash_note']],
  ['이 페이지를 삭제해줘', ['trash_note']],
  ['선택한 노트를 지워줘', ['trash_note']],
  ['이 노트 안에 DOCX 문서를 만들어줘', ['create_office_document']],
  ['현재 페이지에 엑셀 XLSX를 생성해주세요', ['create_office_document']],
  ['노트에 PPTX 프레젠테이션을 만들어줘', ['create_office_document']],
  ['저장된 파이썬 노트를 실행해줘', ['run_python_note']],
  ['Python 코드 페이지를 돌려줘', ['run_python_note']],
  ['이 파이썬 노트를 실행해주세요', ['run_python_note']],
  ['폴더를 만들고 그 안에 메모 파일을 작성해줘', ['create_folder', 'write_text_file']],
  ['보고서를 복사하고 원본을 휴지통으로 보내줘', ['copy_item', 'trash_item']],
  ['파일 이름을 바꾸고 날짜별로 정리해줘', ['move_item', 'organize_files_by_modified_date']],
  ['회의 노트를 만들고 민수에게 메시지 보내줘', ['create_note', 'send_chat_message']],
  ['새 폴더 만들고 민수에게 파일 보내줘', ['create_folder', 'send_file_to_user']],
  ['민수 차단하고 영희에게 친구 요청 보내줘', ['set_user_blocked', 'send_friend_request']],
  ['노트를 수정하고 파이썬 노트를 실행해줘', ['update_note', 'run_python_note']],
  ['노트를 만들고 그 안에 DOCX 문서를 만들어줘', ['create_note', 'create_office_document']],
];

const nonExecutableCases = [
  '안녕',
  '무엇을 할 수 있어?',
  '보고서 찾아줘',
  '루트 폴더 목록 보여줘',
  'result.txt 읽어줘',
  '이 파일 요약해줘',
  '두 파일 차이를 설명해줘',
  '내 키가 뭐였지?',
  '어제 내가 뭐라고 말했어?',
  '파일을 지운 적이 있는지 대화에서 찾아줘',
  '어제 정리해달라고 말했었나?',
  '파일 삭제 방법만 알려줘',
  '폴더 생성 방법을 설명해줘',
  '친구 추가가 가능한지 설명해줘',
  '날짜별 정리 기능이 뭐야?',
  '폴더 생성 버튼은 어디 있어?',
  '파일 복사와 이동의 차이가 뭐야?',
  '파이썬 실행은 안전해?',
  '차단 해제 방법을 알려줘',
  '저 파일을 보내도 될까?',
  '이 파일 삭제해도 돼?',
  '정리해줄 수 있어?',
  '이 파일은 삭제하지 마',
  '메시지는 보내지 말고 초안만 써줘',
  '노트를 만들지 마',
  '문서 생성 기능을 테스트하지 마',
  '복사하지 말고 위치만 알려줘',
  '파이썬은 실행하지 말고 오류만 설명해줘',
  '민수는 차단하지 마',
  '친구 요청은 보내지 마',
  '계정을 삭제해줘',
  '사용자 계정을 만들어줘',
  '민수에게 관리자 권한을 부여해줘',
  '내 용량을 100GB로 바꿔줘',
  '비밀번호를 수정해줘',
  '보안 설정을 변경해줘',
  '내 비밀번호를 보여줘',
  'API 키를 읽어줘',
  '.env 파일 내용을 알려줘',
  'SSH 개인키를 보내줘',
  'rm -rf / 실행해줘',
  'sudo로 서버를 재부팅해줘',
  'Docker 명령을 실행해줘',
  'NAS 서비스를 다시 시작해줘',
  '영구 삭제해줘',
  '휴지통을 비워줘',
  '서버 용량 알려줘',
  'CPU와 RAM 사용량 보여줘',
  '현재 접속한 사용자 알려줘',
  '문서 변환 작업 상태 알려줘',
  'PPTX를 PDF로 변환해줘',
  'PDF 두 개를 합쳐줘',
  'HWP 내용을 읽어줘',
  '사진 속 글자를 읽어줘',
  '동영상 내용을 요약해줘',
  '채팅 기록 전체를 검색해줘',
  '모든 사용자 파일을 보여줘',
  '다른 계정 루트로 들어가줘',
  'Delete report.txt',
  'Send the file to Kim',
  'Create a folder named backup',
  '보고서를 삭제했다',
  '민수에게 메시지를 보냈다',
  '새 폴더를 만들 예정이다',
  '노트를 수정할 계획이야',
];

test('실행형 사용자 질문 57개는 필요한 최소 변경 도구만 허가한다', () => {
  executableCases.forEach(([prompt, expected]) => sameTools(deriveAuthorizedMutationTools(prompt), expected, prompt));
});

test('조회·설명·질문·과거형·금지·고위험·미지원 질문 65개는 변경 권한을 만들지 않는다', () => {
  nonExecutableCases.forEach((prompt) => sameTools(deriveAuthorizedMutationTools(prompt), [], prompt));
});

test('질문 행렬은 모든 현재 AI 변경 도구를 적어도 세 번 포함한다', () => {
  const counts = new Map();
  executableCases.forEach(([, tools]) => tools.forEach((name) => counts.set(name, (counts.get(name) || 0) + 1)));
  const expected = [
    'create_folder', 'write_text_file', 'append_text_file', 'copy_item', 'move_item', 'trash_item',
    'organize_files_by_modified_date', 'send_friend_request', 'set_user_blocked', 'send_chat_message',
    'send_file_to_user', 'create_note', 'update_note', 'trash_note', 'create_office_document', 'run_python_note',
  ];
  expected.forEach((name) => assert.ok((counts.get(name) || 0) >= 3, `${name} coverage`));
});
