const test = require('node:test');
const assert = require('node:assert/strict');
const { deriveAuthorizedMutationTools, _test } = require('../aiAgentRuntime');

const sameTools = (actual, expected, prompt) => assert.deepEqual([...actual].sort(), [...expected].sort(), prompt);

const executableCases = [
  ['새 폴더 만들어줘', ['create_folder']],
  ['/사진/2026 폴더를 생성해주세요', ['create_folder']],
  ['백업 디렉터리 생성해 주세요', ['create_folder']],
  ['보고서.txt 파일을 만들어줘', ['write_text_file']],
  ['/메모.txt 파일에 내용을 저장해줘', ['write_text_file']],
  ['todo.md 파일을 작성해주세요', ['write_text_file']],
  ['기존 메모 끝에 한 줄 추가해줘', ['append_text_file']],
  ['일지 파일에 오늘 기록을 덧붙여줘', ['append_text_file']],
  ['README 내용 끝에 문장을 추가해주세요', ['append_text_file']],
  ['사진 폴더를 백업 폴더로 복사해줘', ['copy_item']],
  ['이 문서를 복제해주세요', ['copy_item']],
  ['report.pdf 사본을 복사해줘', ['copy_item']],
  ['a.txt를 archive로 옮겨줘', ['move_item']],
  ['사진을 보관함으로 이동해주세요', ['move_item']],
  ['old.txt 이름을 new.txt로 바꿔줘', ['move_item']],
  ['old.txt를 삭제해줘', ['trash_item']],
  ['tmp 폴더를 지워줘', ['trash_item']],
  ['report.pdf를 휴지통으로 보내줘', ['trash_item']],
  ['다운로드 폴더를 날짜별로 정리해주세요', ['organize_files_by_modified_date']],
  ['사진 파일을 월별로 분류해줘', ['organize_files_by_modified_date']],
  ['어제 작업 파일을 정리해줘', ['organize_files_by_modified_date']],
  ['민수에게 친구 요청 보내줘', ['send_friend_request']],
  ['영희를 친구로 추가해주세요', ['send_friend_request']],
  ['사용자 kim에게 친구 요청을 전송해줘', ['send_friend_request']],
  ['민수를 차단해줘', ['set_user_blocked']],
  ['영희 차단을 해제해주세요', ['set_user_blocked']],
  ['kim 사용자를 차단해 주세요', ['set_user_blocked']],
  ['민수에게 늦는다고 메시지 보내줘', ['send_chat_message']],
  ['영희에게 안녕이라고 채팅 전송해줘', ['send_chat_message']],
  ['kim에게 회의가 취소됐다고 알려줘', ['send_chat_message']],
  ['민수에게 보고서 파일을 보내줘', ['send_file_to_user']],
  ['영희에게 사진 폴더를 공유해주세요', ['send_file_to_user']],
  ['kim에게 문서를 전송해줘', ['send_file_to_user']],
  ['회의 노트를 만들어줘', ['create_note']],
  ['새 Markdown 페이지를 생성해주세요', ['create_note']],
  ['Python 코드 노트를 작성해줘', ['create_note']],
  ['회의 노트 내용을 수정해줘', ['update_note']],
  ['이 페이지 제목을 바꿔줘', ['update_note']],
  ['선택한 노트를 편집해주세요', ['update_note']],
  ['회의 노트를 휴지통으로 보내줘', ['trash_note']],
  ['이 페이지를 삭제해줘', ['trash_note']],
  ['선택한 노트를 지워줘', ['trash_note']],
  ['이 노트 안에 DOCX 문서를 만들어줘', ['create_office_document']],
  ['현재 페이지에 엑셀 XLSX를 생성해주세요', ['create_office_document']],
  ['노트에 PPTX 프레젠테이션을 만들어줘', ['create_office_document']],
  ['저장된 파이썬 노트를 실행해줘', ['run_python_note']],
  ['Python 코드 페이지를 돌려줘', ['run_python_note']],
  ['이 파이썬 노트를 실행해주세요', ['run_python_note']],
  ['저장된 자바스크립트 노트를 실행해줘', ['run_javascript_note']],
  ['JavaScript 코드 페이지를 돌려줘', ['run_javascript_note']],
  ['이 JS 노트를 실행해주세요', ['run_javascript_note']],
  ['폴더를 만들고 그 안에 메모 파일을 작성해줘', ['create_folder', 'write_text_file']],
  ['보고서를 복사하고 원본을 휴지통으로 보내줘', ['copy_item', 'trash_item']],
  ['파일 이름을 바꾸고 날짜별로 정리해줘', ['move_item', 'organize_files_by_modified_date']],
  ['회의 노트를 만들고 민수에게 메시지 보내줘', ['create_note', 'send_chat_message']],
  ['새 폴더 만들고 민수에게 파일 보내줘', ['create_folder', 'send_file_to_user']],
  ['민수 차단하고 영희에게 친구 요청 보내줘', ['set_user_blocked', 'send_friend_request']],
  ['노트를 수정하고 파이썬 노트를 실행해줘', ['update_note', 'run_python_note']],
  ['노트를 만들고 그 안에 DOCX 문서를 만들어줘', ['create_note', 'create_office_document']],
  ['간증문을 한글 문서로 만들어줘', ['create_document']],
  ['휴지통에서 삭제한 파일을 복원해줘', ['restore_trash_item']],
  ['보고서 파일의 이전 버전을 복원해줘', ['restore_file_version']],
  ['전체 드라이브 복구 지점을 만들어줘', ['create_drive_restore_point']],
  ['전체 드라이브를 복구 지점으로 복원해줘', ['restore_drive_restore_point']],
  ['이 파일을 즐겨찾기에 추가해줘', ['set_file_favorite']],
  ['받은 친구 요청을 수락해줘', ['accept_friend_request']],
  ['받은 친구 요청을 거절해줘', ['reject_friend_request']],
  ['민수를 친구에서 제거해줘', ['remove_friend']],
  ['민수 친구를 즐겨찾기에 추가해줘', ['set_friend_favorite']],
  ['이 알림을 읽음 처리해줘', ['mark_notification_read']],
  ['모든 알림을 읽음 처리해줘', ['mark_all_notifications_read']],
  ['개발 노트북을 만들어줘', ['create_notebook']],
  ['휴지통의 노트를 복원해줘', ['restore_note']],
  ['노트의 이전 버전을 복원해줘', ['restore_note_version']],
  ['이 파일을 노트에 첨부해줘', ['attach_note_item']],
  ['노트 첨부를 제거해줘', ['remove_note_attachment']],
  ['문서 변환 작업을 취소해줘', ['cancel_document_job']],
  ['문서 변환 작업을 재시도해줘', ['retry_document_job']],
  ['이 문서를 PDF로 변환해줘', ['create_document_job']],
  ['이 PC 동기화를 일시 정지해줘', ['set_device_sync']],
  ['이 PC 연결을 해제해줘', ['revoke_device']],
  ['이 폴더의 공유 링크를 만들어줘', ['create_share_link']],
  ['공유 링크를 일시 정지해줘', ['set_share_paused']],
  ['공유 링크를 비활성화해줘', ['revoke_share_link']],
  ['민수와 영희를 초대해서 그룹 채팅방을 만들어줘', ['create_group_chat']],
  ['개발 채팅방에 민수를 초대해줘', ['invite_group_chat']],
  ['그룹 채팅 초대를 수락해줘', ['respond_group_invite']],
  ['이 그룹 채팅방에서 나가줘', ['leave_group_chat']],
  ['이 그룹 채팅방에 안녕하세요 메시지를 보내줘', ['send_group_message']],
  ['민수 사용자 용량을 20GB로 변경해줘', ['update_managed_user']],
  ['신규 계정 가입을 승인해줘', ['approve_signup']],
  ['이 가입 요청을 거절해줘', ['reject_signup']],
  ['서버 자원 제한 정책을 자동으로 설정해줘', ['set_resource_policy']],
  ['자동 로그인을 켜줘', ['set_login_persistence']],
  ['내 프로필 닉네임을 찬영으로 바꿔줘', ['update_profile']],
  ['이 채팅방 방장을 민수에게 위임해줘', ['transfer_group_owner']],
  ['이 채팅방에 민수를 부방장으로 지정해줘', ['set_group_cohost']],
  ['민수를 이 그룹 채팅방에서 내보내줘', ['kick_group_member']],
  ['이 그룹 채팅방을 파기해줘', ['delete_group_chat']],
  ['이 화상회의 공개 설정을 변경해줘', ['configure_meeting']],
  ['이 채팅방 회의를 시작해줘', ['start_meeting']],
  ['이 임시 회의를 정규 회의로 저장해줘', ['save_meeting']],
  ['이 채팅 메시지의 받은 파일을 저장해줘', ['save_chat_attachments']],
  ['이 채팅방을 읽음 처리해줘', ['mark_chat_read']],
  ['이 공유 링크 만료일을 변경해줘', ['update_share_link']],
  ['이 공유 링크 주소를 재발급해줘', ['regenerate_share_token']],
];

const nonExecutableCases = [
  '안녕',
  '무엇을 할 수 있어?',
  '보고서 찾아줘',
  '루트 폴더 목록 보여줘',
  'result.txt 읽어줘',
  '이 파일 요약해줘',
  '두 파일 차이를 설명해줘',
  '내 키가 뭐였지?',
  '어제 내가 뭐라고 말했어?',
  '파일을 지운 적이 있는지 대화에서 찾아줘',
  '어제 정리해달라고 말했었나?',
  '파일 삭제 방법만 알려줘',
  '폴더 생성 방법을 설명해줘',
  '친구 추가가 가능한지 설명해줘',
  '날짜별 정리 기능이 뭐야?',
  '폴더 생성 버튼은 어디 있어?',
  '파일 복사와 이동의 차이가 뭐야?',
  '파이썬 실행은 안전해?',
  '차단 해제 방법을 알려줘',
  '저 파일을 보내도 될까?',
  '이 파일 삭제해도 돼?',
  '정리해줄 수 있어?',
  '이 파일은 삭제하지 마',
  '메시지는 보내지 말고 초안만 써줘',
  '노트를 만들지 마',
  '문서 생성 기능을 테스트하지 마',
  '복사하지 말고 위치만 알려줘',
  '파이썬은 실행하지 말고 오류만 설명해줘',
  '민수는 차단하지 마',
  '친구 요청은 보내지 마',
  '계정을 삭제해줘',
  '사용자 계정을 만들어줘',
  '민수에게 관리자 권한을 부여해줘',
  '내 용량을 100GB로 바꿔줘',
  '비밀번호를 수정해줘',
  '보안 설정을 변경해줘',
  '내 비밀번호를 보여줘',
  'API 키를 읽어줘',
  '.env 파일 내용을 알려줘',
  'SSH 개인키를 보내줘',
  'rm -rf / 실행해줘',
  'sudo로 서버를 재부팅해줘',
  'Docker 명령을 실행해줘',
  'NAS 서비스를 다시 시작해줘',
  '영구 삭제해줘',
  '휴지통을 비워줘',
  '서버 용량 알려줘',
  'CPU와 RAM 사용량 보여줘',
  '현재 접속한 사용자 알려줘',
  '문서 변환 작업 상태 알려줘',
  'HWP 내용을 읽어줘',
  '사진 속 글자를 읽어줘',
  '동영상 내용을 요약해줘',
  '채팅 기록 전체를 검색해줘',
  '모든 사용자 파일을 보여줘',
  '다른 계정 루트로 들어가줘',
  'Delete report.txt',
  'Send the file to Kim',
  'Create a folder named backup',
  '보고서를 삭제했다',
  '민수에게 메시지를 보냈다',
  '새 폴더를 만들 예정이다',
  '노트를 수정할 계획이야',
];

test('실행형 사용자 질문은 필요한 최소 변경 도구만 허가한다', () => {
  executableCases.forEach(([prompt, expected]) => sameTools(deriveAuthorizedMutationTools(prompt), expected, prompt));
});

test('조회·설명·질문·과거형·금지·미지원 질문은 변경 권한을 만들지 않는다', () => {
  nonExecutableCases.forEach((prompt) => sameTools(deriveAuthorizedMutationTools(prompt), [], prompt));
});

test('질문 행렬은 기존 핵심 도구를 반복 검증하고 모든 현재 변경 도구를 포함한다', () => {
  const counts = new Map();
  executableCases.forEach(([, tools]) => tools.forEach((name) => counts.set(name, (counts.get(name) || 0) + 1)));
  const expected = [
    'create_folder', 'write_text_file', 'append_text_file', 'copy_item', 'move_item', 'trash_item',
    'organize_files_by_modified_date', 'send_friend_request', 'set_user_blocked', 'send_chat_message',
    'send_file_to_user', 'create_note', 'update_note', 'trash_note', 'create_office_document', 'run_python_note', 'run_javascript_note',
  ];
  expected.forEach((name) => assert.ok((counts.get(name) || 0) >= 3, `${name} coverage`));
  _test.MUTATION_TOOL_NAMES.forEach((name) => assert.ok((counts.get(name) || 0) >= 1, `${name} has no intent test`));
});
